language: erlang

env:
  - LUA="5.1"

branches:
  only:
    - master

install:
  - sudo apt-get install luajit
  - sudo apt-get install lua-unit
  - sudo apt-get install lua-bitop
  - sudo apt-get install lua5.1
  
script:
  - lua test/testiptools.lua

notifications:
  email:
    on_success: change
    on_failure: always