language: erlang

env:
  - LUA=""
  - LUA="luajit"

branches:
  only:
    - master

install:
  - sudo apt-get install luajit
  - sudo apt-get install lua-unit
  - sudo apt-get install lua-bitop
  
script:
  - lua test/testiptools.lua

notifications:
  email:
    on_success: change
    on_failure: always